name: test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [8, 10, 12]
        tz: ["Z", "UTC", "Asia/Tokyo", "Pacific/Pago_Pago", "America/Los_Angeles"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/cache@master
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - run: |
          yarn install
          yarn tsc
          yarn test
        env:
          TZ: ${{ matrix.tz }}
